import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

type CategorySeed = {
  name: string
  slug: string
  description: string
}

type BrandSeed = {
  name: string
  slug: string
  description: string
}

type ProductSeed = {
  name: string
  slug: string
  sku: string
  categorySlug: string
  brandSlug?: string
  shortDescription: string
  description: string
  mrp: number
  sellingPrice: number
  discountPrice?: number
  gstPercentage: number
  stockQuantity: number
  isFeatured?: boolean
  imageCount: number
  specifications: Array<{ name: string; value: string }>
}

const categories: CategorySeed[] = [
  {
    name: 'Basic Electronic Components',
    slug: 'basic-electronic-components',
    description: 'Core passive and discrete components used in day-to-day circuit design and repair.',
  },
  {
    name: 'Integrated Circuits',
    slug: 'integrated-circuits',
    description: 'Timer ICs, logic ICs, controllers, and supporting integrated semiconductors.',
  },
  {
    name: 'Power Supply Components',
    slug: 'power-supply-components',
    description: 'Power conversion, backup, and regulation components for electronics systems.',
  },
  {
    name: 'Display Components',
    slug: 'display-components',
    description: 'Panels, modules, and interactive display parts for embedded and consumer builds.',
  },
  {
    name: 'Sensors',
    slug: 'sensors',
    description: 'Detection and measurement sensors for automation, robotics, and smart projects.',
  },
  {
    name: 'Connectors & Wiring',
    slug: 'connectors-and-wiring',
    description: 'Connectivity essentials for assembly, prototyping, and durable field wiring.',
  },
  {
    name: 'Audio Components',
    slug: 'audio-components',
    description: 'Modules and transducers used in audio playback, capture, and alerts.',
  },
  {
    name: 'Communication Modules',
    slug: 'communication-modules',
    description: 'Wireless and network-ready modules for connected electronics applications.',
  },
  {
    name: 'Computer and PCB Components',
    slug: 'computer-and-pcb-components',
    description: 'Fabrication, prototyping, cooling, and assembly parts for PCB and system builds.',
  },
  {
    name: 'Industrial Electronics Components',
    slug: 'industrial-electronics-components',
    description: 'Industrial-grade control, drive, and protection hardware for automation systems.',
  },
]

const brands: BrandSeed[] = [
  { name: 'Yashi', slug: 'yashi', description: 'In-house curated catalogue brand for dependable electronics supply.' },
  { name: 'Generic', slug: 'generic', description: 'General-purpose component line for value-conscious builds.' },
  { name: 'Samsung', slug: 'samsung', description: 'Display and electronics brand used in selected modules and components.' },
  { name: 'LG', slug: 'lg', description: 'Trusted electronics manufacturing brand for displays and power parts.' },
  { name: 'Sony', slug: 'sony', description: 'Premium electronics brand for audio and communication accessories.' },
  { name: 'Philips', slug: 'philips', description: 'Established brand for lighting, audio, and electronics support components.' },
  { name: 'Panasonic', slug: 'panasonic', description: 'Industrial and consumer electronics brand with reliable component lines.' },
  { name: 'Omron', slug: 'omron', description: 'Industrial controls and switching components used in automation systems.' },
  { name: 'Siemens', slug: 'siemens', description: 'Industrial automation and control systems brand.' },
  { name: 'Schneider', slug: 'schneider', description: 'Electrical protection and industrial infrastructure brand.' },
  { name: 'Dell', slug: 'dell', description: 'Systems and accessories brand used for selected computer-oriented items.' },
  { name: 'HP', slug: 'hp', description: 'System component brand used for select computing support products.' },
]

const placeholderImageUrl = (productName: string, imageIndex: number) => {
  const text = encodeURIComponent(`${productName} ${imageIndex}`)
  return `https://placehold.co/900x900/e2e8f0/0f172a/png?text=${text}`
}

const products: ProductSeed[] = [
  {
    name: 'Carbon Film Resistor Kit 1/4W',
    slug: 'carbon-film-resistor-kit-1-4w',
    sku: 'YEC-BEC-001',
    categorySlug: 'basic-electronic-components',
    brandSlug: 'yashi',
    shortDescription: 'Assorted 1/4 watt resistor pack for prototyping, repair, and lab use.',
    description: 'A sorted resistor assortment covering frequently used resistance values for breadboards, learning kits, and small product development work.',
    mrp: 249,
    sellingPrice: 199,
    discountPrice: 179,
    gstPercentage: 18,
    stockQuantity: 120,
    isFeatured: true,
    imageCount: 2,
    specifications: [
      { name: 'Wattage', value: '0.25W' },
      { name: 'Tolerance', value: '5%' },
      { name: 'Resistor Type', value: 'Carbon film' },
      { name: 'Pack Size', value: '600 pieces assorted' },
    ],
  },
  {
    name: 'Electrolytic Capacitor Assortment Pack',
    slug: 'electrolytic-capacitor-assortment-pack',
    sku: 'YEC-BEC-002',
    categorySlug: 'basic-electronic-components',
    brandSlug: 'generic',
    shortDescription: 'Mixed capacitor pack for power, audio, and general circuit repair.',
    description: 'A practical capacitor assortment containing high-rotation values used in power supply boards, audio amplifiers, and restoration work.',
    mrp: 399,
    sellingPrice: 325,
    gstPercentage: 18,
    stockQuantity: 42,
    imageCount: 2,
    specifications: [
      { name: 'Capacitor Type', value: 'Electrolytic radial' },
      { name: 'Voltage Range', value: '16V to 50V' },
      { name: 'Values Included', value: '1uF to 1000uF' },
      { name: 'Pack Size', value: '120 pieces assorted' },
    ],
  },
  {
    name: 'General Purpose Diode 1N4007 Pack',
    slug: 'general-purpose-diode-1n4007-pack',
    sku: 'YEC-BEC-003',
    categorySlug: 'basic-electronic-components',
    brandSlug: 'philips',
    shortDescription: 'Reliable rectifier diode pack for adapters, chargers, and hobby circuits.',
    description: 'A field-ready 1N4007 pack suitable for rectification, reverse polarity protection, and repair jobs across consumer and lab electronics.',
    mrp: 149,
    sellingPrice: 119,
    discountPrice: 99,
    gstPercentage: 18,
    stockQuantity: 200,
    imageCount: 1,
    specifications: [
      { name: 'Part Number', value: '1N4007' },
      { name: 'Reverse Voltage', value: '1000V' },
      { name: 'Forward Current', value: '1A' },
      { name: 'Package', value: 'DO-41 axial' },
    ],
  },
  {
    name: '12V Miniature Relay Module',
    slug: '12v-miniature-relay-module',
    sku: 'YEC-BEC-004',
    categorySlug: 'basic-electronic-components',
    brandSlug: 'omron',
    shortDescription: 'Compact switching relay module for automation panels and control boards.',
    description: 'A dependable relay module designed for low-voltage control switching in security systems, automation boards, and prototyping fixtures.',
    mrp: 189,
    sellingPrice: 159,
    gstPercentage: 18,
    stockQuantity: 4,
    imageCount: 2,
    specifications: [
      { name: 'Coil Voltage', value: '12V DC' },
      { name: 'Contact Rating', value: '10A at 250V AC' },
      { name: 'Mounting', value: 'PCB mount' },
      { name: 'Switch Type', value: 'SPDT' },
    ],
  },
  {
    name: 'NE555 Timer IC DIP-8',
    slug: 'ne555-timer-ic-dip-8',
    sku: 'YEC-IC-001',
    categorySlug: 'integrated-circuits',
    brandSlug: 'yashi',
    shortDescription: 'Classic timer IC for delay, pulse, oscillator, and control circuits.',
    description: 'The NE555 remains a versatile building block for timing and pulse generation in training boards, products, and service applications.',
    mrp: 35,
    sellingPrice: 28,
    gstPercentage: 18,
    stockQuantity: 300,
    isFeatured: true,
    imageCount: 1,
    specifications: [
      { name: 'Package', value: 'DIP-8' },
      { name: 'Supply Voltage', value: '4.5V to 16V' },
      { name: 'Application', value: 'Astable and monostable timing' },
      { name: 'Operating Temp', value: '-55C to 125C' },
    ],
  },
  {
    name: 'LM358 Dual Op-Amp IC',
    slug: 'lm358-dual-op-amp-ic',
    sku: 'YEC-IC-002',
    categorySlug: 'integrated-circuits',
    brandSlug: 'generic',
    shortDescription: 'Low-power dual op-amp for sensor conditioning and analog processing.',
    description: 'Widely used dual operational amplifier suitable for battery-powered circuits, signal conditioning, and analog interface boards.',
    mrp: 32,
    sellingPrice: 26,
    discountPrice: 24,
    gstPercentage: 18,
    stockQuantity: 180,
    imageCount: 1,
    specifications: [
      { name: 'Channels', value: 'Dual op-amp' },
      { name: 'Supply Voltage', value: '3V to 32V' },
      { name: 'Package', value: 'DIP-8' },
      { name: 'Typical Use', value: 'Comparator and amplifier circuits' },
    ],
  },
  {
    name: 'ATmega328P Microcontroller',
    slug: 'atmega328p-microcontroller',
    sku: 'YEC-IC-003',
    categorySlug: 'integrated-circuits',
    brandSlug: 'panasonic',
    shortDescription: 'Popular 8-bit microcontroller for embedded prototypes and control products.',
    description: 'A trusted microcontroller for education, embedded control, and custom electronics that need efficient GPIO, timers, and serial interfaces.',
    mrp: 329,
    sellingPrice: 289,
    discountPrice: 269,
    gstPercentage: 18,
    stockQuantity: 22,
    imageCount: 2,
    specifications: [
      { name: 'Core', value: '8-bit AVR' },
      { name: 'Flash Memory', value: '32KB' },
      { name: 'Package', value: 'DIP-28' },
      { name: 'Clock Speed', value: 'Up to 20 MHz' },
    ],
  },
  {
    name: '7805 Voltage Regulator IC',
    slug: '7805-voltage-regulator-ic',
    sku: 'YEC-IC-004',
    categorySlug: 'integrated-circuits',
    brandSlug: 'philips',
    shortDescription: '5V linear regulator IC for simple regulated supply designs.',
    description: 'A staple regulator IC for fixed 5V supply rails in control boards, lab builds, and repair-friendly electronics products.',
    mrp: 25,
    sellingPrice: 20,
    gstPercentage: 18,
    stockQuantity: 0,
    imageCount: 1,
    specifications: [
      { name: 'Output Voltage', value: '5V fixed' },
      { name: 'Output Current', value: 'Up to 1A with heatsink' },
      { name: 'Package', value: 'TO-220' },
      { name: 'Protection', value: 'Thermal shutdown and current limit' },
    ],
  },
  {
    name: '12V 7Ah Sealed Lead Acid Battery',
    slug: '12v-7ah-sealed-lead-acid-battery',
    sku: 'YEC-PSC-001',
    categorySlug: 'power-supply-components',
    brandSlug: 'yashi',
    shortDescription: 'Maintenance-free battery for UPS backup, alarms, and emergency power.',
    description: 'A compact SLA battery suited for backup systems, emergency lighting, access control, and small inverter support tasks.',
    mrp: 1799,
    sellingPrice: 1549,
    discountPrice: 1499,
    gstPercentage: 18,
    stockQuantity: 18,
    isFeatured: true,
    imageCount: 2,
    specifications: [
      { name: 'Battery Type', value: 'Sealed lead acid' },
      { name: 'Voltage', value: '12V' },
      { name: 'Capacity', value: '7Ah' },
      { name: 'Use Case', value: 'UPS, security, emergency backup' },
    ],
  },
  {
    name: '24V 5A SMPS Power Supply',
    slug: '24v-5a-smps-power-supply',
    sku: 'YEC-PSC-002',
    categorySlug: 'power-supply-components',
    brandSlug: 'schneider',
    shortDescription: 'Industrial switching power supply for CNC, automation, and LED systems.',
    description: 'An enclosed metal-case SMPS delivering stable 24V output for automation control panels, machines, and field installations.',
    mrp: 2499,
    sellingPrice: 2190,
    gstPercentage: 18,
    stockQuantity: 9,
    imageCount: 2,
    specifications: [
      { name: 'Output', value: '24V DC / 5A' },
      { name: 'Input Range', value: '110V to 240V AC' },
      { name: 'Cooling', value: 'Passive ventilation' },
      { name: 'Protection', value: 'Overload and short circuit' },
    ],
  },
  {
    name: '12V 2A DC Adapter',
    slug: '12v-2a-dc-adapter',
    sku: 'YEC-PSC-003',
    categorySlug: 'power-supply-components',
    brandSlug: 'generic',
    shortDescription: 'Compact adapter for routers, cameras, and low-voltage electronics.',
    description: 'A reliable plug-in adapter offering regulated 12V output for routers, CCTV systems, hobby boards, and compact devices.',
    mrp: 449,
    sellingPrice: 369,
    discountPrice: 329,
    gstPercentage: 18,
    stockQuantity: 60,
    imageCount: 1,
    specifications: [
      { name: 'Output', value: '12V DC / 2A' },
      { name: 'Connector', value: '5.5mm x 2.1mm barrel jack' },
      { name: 'Input', value: '100V to 240V AC' },
      { name: 'Cable Length', value: '1.2 meters' },
    ],
  },
  {
    name: 'Bridge Rectifier 10A Module',
    slug: 'bridge-rectifier-10a-module',
    sku: 'YEC-PSC-004',
    categorySlug: 'power-supply-components',
    brandSlug: 'panasonic',
    shortDescription: 'Robust rectifier block for AC to DC conversion stages.',
    description: 'A panel-friendly bridge rectifier module built for rectification sections in chargers, bench supplies, and control boards.',
    mrp: 119,
    sellingPrice: 95,
    gstPercentage: 18,
    stockQuantity: 5,
    imageCount: 1,
    specifications: [
      { name: 'Current Rating', value: '10A' },
      { name: 'Voltage Rating', value: '1000V PIV' },
      { name: 'Mounting', value: 'Chassis or heat sink mount' },
      { name: 'Application', value: 'AC to DC conversion' },
    ],
  },
  {
    name: '16x2 LCD Display Module',
    slug: '16x2-lcd-display-module',
    sku: 'YEC-DSP-001',
    categorySlug: 'display-components',
    brandSlug: 'yashi',
    shortDescription: 'Classic character LCD for embedded systems, control panels, and learning kits.',
    description: 'A standard 16x2 display module suitable for microcontroller projects, device panels, and classroom electronics demos.',
    mrp: 199,
    sellingPrice: 159,
    discountPrice: 149,
    gstPercentage: 18,
    stockQuantity: 30,
    isFeatured: true,
    imageCount: 2,
    specifications: [
      { name: 'Display Format', value: '16 characters x 2 lines' },
      { name: 'Backlight', value: 'Blue with white text' },
      { name: 'Interface', value: 'Parallel HD44780 compatible' },
      { name: 'Operating Voltage', value: '5V DC' },
    ],
  },
  {
    name: '0.96 Inch OLED Display I2C',
    slug: '0-96-inch-oled-display-i2c',
    sku: 'YEC-DSP-002',
    categorySlug: 'display-components',
    brandSlug: 'samsung',
    shortDescription: 'Compact OLED module with sharp contrast for embedded dashboards.',
    description: 'A crisp monochrome OLED display offering low-power operation and easy I2C integration for compact electronics projects.',
    mrp: 349,
    sellingPrice: 299,
    gstPercentage: 18,
    stockQuantity: 14,
    imageCount: 2,
    specifications: [
      { name: 'Size', value: '0.96 inch' },
      { name: 'Resolution', value: '128 x 64' },
      { name: 'Interface', value: 'I2C' },
      { name: 'Color', value: 'White/blue OLED' },
    ],
  },
  {
    name: 'Four Digit Seven Segment Display',
    slug: 'four-digit-seven-segment-display',
    sku: 'YEC-DSP-003',
    categorySlug: 'display-components',
    brandSlug: 'generic',
    shortDescription: 'Multi-digit display for counters, clocks, and compact readouts.',
    description: 'A bright seven-segment module well suited for numeric displays, timers, and value readouts in embedded products.',
    mrp: 139,
    sellingPrice: 112,
    discountPrice: 99,
    gstPercentage: 18,
    stockQuantity: 70,
    imageCount: 1,
    specifications: [
      { name: 'Digits', value: '4-digit' },
      { name: 'Display Color', value: 'Red LED' },
      { name: 'Mounting', value: 'PCB through-hole' },
      { name: 'Use Case', value: 'Clocks, counters, measurement devices' },
    ],
  },
  {
    name: '5 Inch Capacitive Touch Screen',
    slug: '5-inch-capacitive-touch-screen',
    sku: 'YEC-DSP-004',
    categorySlug: 'display-components',
    brandSlug: 'lg',
    shortDescription: 'Compact touch display panel for HMI builds and kiosks.',
    description: 'A slim capacitive touch panel designed for interactive interfaces, compact HMIs, and custom equipment dashboards.',
    mrp: 2899,
    sellingPrice: 2499,
    gstPercentage: 18,
    stockQuantity: 3,
    imageCount: 3,
    specifications: [
      { name: 'Screen Size', value: '5 inches' },
      { name: 'Touch Type', value: 'Capacitive multi-touch' },
      { name: 'Resolution', value: '800 x 480' },
      { name: 'Application', value: 'HMI, kiosks, instrumentation' },
    ],
  },
  {
    name: 'DS18B20 Waterproof Temperature Sensor',
    slug: 'ds18b20-waterproof-temperature-sensor',
    sku: 'YEC-SEN-001',
    categorySlug: 'sensors',
    brandSlug: 'yashi',
    shortDescription: 'Digital temperature probe for outdoor, industrial, and project applications.',
    description: 'A waterproof temperature sensor built for monitoring liquids, ambient conditions, and equipment enclosures with simple digital interfacing.',
    mrp: 149,
    sellingPrice: 129,
    gstPercentage: 18,
    stockQuantity: 55,
    imageCount: 2,
    specifications: [
      { name: 'Sensor Type', value: 'Digital temperature sensor' },
      { name: 'Range', value: '-55C to 125C' },
      { name: 'Interface', value: '1-Wire' },
      { name: 'Probe Length', value: '1 meter cable' },
    ],
  },
  {
    name: 'PIR Motion Sensor Module',
    slug: 'pir-motion-sensor-module',
    sku: 'YEC-SEN-002',
    categorySlug: 'sensors',
    brandSlug: 'generic',
    shortDescription: 'Motion detection module for lighting, alarms, and occupancy systems.',
    description: 'An easy-to-integrate PIR module for automatic lighting, security alerts, and motion-triggered control applications.',
    mrp: 99,
    sellingPrice: 79,
    discountPrice: 69,
    gstPercentage: 18,
    stockQuantity: 88,
    imageCount: 1,
    specifications: [
      { name: 'Detection Type', value: 'Passive infrared' },
      { name: 'Trigger Distance', value: 'Up to 7 meters' },
      { name: 'Operating Voltage', value: '5V to 20V DC' },
      { name: 'Adjustments', value: 'Sensitivity and delay' },
    ],
  },
  {
    name: 'HC-SR04 Ultrasonic Sensor',
    slug: 'hc-sr04-ultrasonic-sensor',
    sku: 'YEC-SEN-003',
    categorySlug: 'sensors',
    brandSlug: 'sony',
    shortDescription: 'Distance measurement module for robotics and automation projects.',
    description: 'A well-known ultrasonic ranging sensor for obstacle detection, distance logging, and automation training systems.',
    mrp: 129,
    sellingPrice: 105,
    gstPercentage: 18,
    stockQuantity: 26,
    imageCount: 1,
    specifications: [
      { name: 'Measurement Range', value: '2cm to 400cm' },
      { name: 'Operating Voltage', value: '5V DC' },
      { name: 'Output', value: 'TTL echo pulse' },
      { name: 'Use Case', value: 'Robotics and obstacle sensing' },
    ],
  },
  {
    name: 'MQ-2 Gas Sensor Module',
    slug: 'mq-2-gas-sensor-module',
    sku: 'YEC-SEN-004',
    categorySlug: 'sensors',
    brandSlug: 'philips',
    shortDescription: 'Gas detection module for LPG, smoke, and flammable gas sensing.',
    description: 'A practical gas sensor board for safety projects, environmental detection, and alert prototypes involving smoke and LPG presence.',
    mrp: 169,
    sellingPrice: 139,
    gstPercentage: 18,
    stockQuantity: 0,
    imageCount: 2,
    specifications: [
      { name: 'Target Gases', value: 'LPG, propane, hydrogen, smoke' },
      { name: 'Output', value: 'Analog and digital' },
      { name: 'Operating Voltage', value: '5V DC' },
      { name: 'Board Feature', value: 'Adjustable sensitivity' },
    ],
  },
  {
    name: 'USB Type-C Female Breakout Connector',
    slug: 'usb-type-c-female-breakout-connector',
    sku: 'YEC-CNW-001',
    categorySlug: 'connectors-and-wiring',
    brandSlug: 'yashi',
    shortDescription: 'Breakout connector for charging, prototyping, and compact integrations.',
    description: 'A board-mount USB Type-C breakout connector that simplifies lab experiments, charging interfaces, and prototype integrations.',
    mrp: 89,
    sellingPrice: 72,
    discountPrice: 69,
    gstPercentage: 18,
    stockQuantity: 110,
    imageCount: 2,
    specifications: [
      { name: 'Connector Type', value: 'USB Type-C female' },
      { name: 'Board Style', value: 'Breakout module' },
      { name: 'Application', value: 'Charging and prototyping' },
      { name: 'Mounting', value: 'Through-hole breakout pads' },
    ],
  },
  {
    name: 'HDMI Panel Mount Connector',
    slug: 'hdmi-panel-mount-connector',
    sku: 'YEC-CNW-002',
    categorySlug: 'connectors-and-wiring',
    brandSlug: 'samsung',
    shortDescription: 'Panel-mount HDMI connector for embedded displays and AV systems.',
    description: 'A secure HDMI connector option for custom display enclosures, kiosks, test systems, and multimedia equipment.',
    mrp: 249,
    sellingPrice: 209,
    gstPercentage: 18,
    stockQuantity: 16,
    imageCount: 1,
    specifications: [
      { name: 'Connector Type', value: 'HDMI female panel mount' },
      { name: 'Signal Support', value: 'High-speed HDMI' },
      { name: 'Mounting', value: 'Screw-lock panel flange' },
      { name: 'Use Case', value: 'AV and embedded display systems' },
    ],
  },
  {
    name: '5 Pin Terminal Block Connector',
    slug: '5-pin-terminal-block-connector',
    sku: 'YEC-CNW-003',
    categorySlug: 'connectors-and-wiring',
    brandSlug: 'schneider',
    shortDescription: 'Screw terminal block for secure field wiring and board connections.',
    description: 'A durable terminal block connector intended for maintenance-friendly field wiring, control boards, and electrical cabinets.',
    mrp: 39,
    sellingPrice: 32,
    gstPercentage: 18,
    stockQuantity: 240,
    imageCount: 1,
    specifications: [
      { name: 'Positions', value: '5 pin' },
      { name: 'Pitch', value: '5.08mm' },
      { name: 'Wire Type', value: 'Screw clamp' },
      { name: 'Application', value: 'Control boards and distribution' },
    ],
  },
  {
    name: '40 Pin Male to Female Jumper Wire Set',
    slug: '40-pin-male-to-female-jumper-wire-set',
    sku: 'YEC-CNW-004',
    categorySlug: 'connectors-and-wiring',
    brandSlug: 'generic',
    shortDescription: 'Breadboard-ready jumper wire set for quick wiring and testing.',
    description: 'A flexible jumper wire kit useful in prototyping, demos, training labs, and compact bench-top development work.',
    mrp: 119,
    sellingPrice: 95,
    discountPrice: 89,
    gstPercentage: 18,
    stockQuantity: 150,
    imageCount: 2,
    specifications: [
      { name: 'Length', value: '20cm' },
      { name: 'Connector Ends', value: 'Male to female' },
      { name: 'Pin Count', value: '40 wires' },
      { name: 'Use Case', value: 'Breadboards and MCU boards' },
    ],
  },
  {
    name: '8 Ohm 5W Mini Speaker',
    slug: '8-ohm-5w-mini-speaker',
    sku: 'YEC-AUD-001',
    categorySlug: 'audio-components',
    brandSlug: 'sony',
    shortDescription: 'Compact speaker driver for embedded alerts and small audio builds.',
    description: 'A miniature speaker suited for embedded voice playback, compact audio output, intercoms, and smart appliance feedback tones.',
    mrp: 149,
    sellingPrice: 124,
    gstPercentage: 18,
    stockQuantity: 34,
    imageCount: 1,
    specifications: [
      { name: 'Impedance', value: '8 Ohm' },
      { name: 'Power Rating', value: '5W' },
      { name: 'Mounting', value: 'Chassis mount' },
      { name: 'Application', value: 'Embedded audio and alerts' },
    ],
  },
  {
    name: 'Electret Condenser Microphone Module',
    slug: 'electret-condenser-microphone-module',
    sku: 'YEC-AUD-002',
    categorySlug: 'audio-components',
    brandSlug: 'philips',
    shortDescription: 'Microphone module for voice capture, sensing, and embedded input.',
    description: 'A compact microphone board that simplifies audio input, sound detection, and voice-related prototyping work.',
    mrp: 109,
    sellingPrice: 89,
    discountPrice: 79,
    gstPercentage: 18,
    stockQuantity: 47,
    imageCount: 1,
    specifications: [
      { name: 'Microphone Type', value: 'Electret condenser' },
      { name: 'Output', value: 'Analog signal' },
      { name: 'Operating Voltage', value: '3.3V to 5V' },
      { name: 'Use Case', value: 'Voice and sound detection' },
    ],
  },
  {
    name: '5V Active Buzzer Module',
    slug: '5v-active-buzzer-module',
    sku: 'YEC-AUD-003',
    categorySlug: 'audio-components',
    brandSlug: 'generic',
    shortDescription: 'Plug-and-play buzzer for alarms, alerts, and status signalling.',
    description: 'An active buzzer module for warning indicators, event alerts, and educational electronics builds with quick logic-level control.',
    mrp: 59,
    sellingPrice: 45,
    gstPercentage: 18,
    stockQuantity: 180,
    imageCount: 1,
    specifications: [
      { name: 'Operating Voltage', value: '5V DC' },
      { name: 'Buzzer Type', value: 'Active' },
      { name: 'Sound Output', value: 'Approx. 85 dB' },
      { name: 'Application', value: 'Alerts and alarms' },
    ],
  },
  {
    name: 'PAM8403 Stereo Amplifier Module',
    slug: 'pam8403-stereo-amplifier-module',
    sku: 'YEC-AUD-004',
    categorySlug: 'audio-components',
    brandSlug: 'panasonic',
    shortDescription: 'Compact stereo amplifier board for portable audio systems.',
    description: 'A low-power stereo amplifier module ideal for handheld builds, small speakers, and audio enhancement projects.',
    mrp: 129,
    sellingPrice: 105,
    gstPercentage: 18,
    stockQuantity: 8,
    imageCount: 2,
    specifications: [
      { name: 'Amplifier IC', value: 'PAM8403' },
      { name: 'Output Power', value: '3W x 2' },
      { name: 'Operating Voltage', value: '2.5V to 5.5V' },
      { name: 'Use Case', value: 'Portable speaker systems' },
    ],
  },
  {
    name: 'ESP8266 Wi-Fi Module',
    slug: 'esp8266-wi-fi-module',
    sku: 'YEC-COM-001',
    categorySlug: 'communication-modules',
    brandSlug: 'yashi',
    shortDescription: 'Affordable Wi-Fi module for IoT prototypes and connected devices.',
    description: 'A widely used Wi-Fi module for remote monitoring, smart controls, and lightweight network-enabled electronics.',
    mrp: 229,
    sellingPrice: 189,
    discountPrice: 179,
    gstPercentage: 18,
    stockQuantity: 53,
    isFeatured: true,
    imageCount: 2,
    specifications: [
      { name: 'Connectivity', value: '2.4GHz Wi-Fi' },
      { name: 'Interface', value: 'UART' },
      { name: 'Operating Voltage', value: '3.3V DC' },
      { name: 'Use Case', value: 'IoT and automation' },
    ],
  },
  {
    name: 'HC-05 Bluetooth Module',
    slug: 'hc-05-bluetooth-module',
    sku: 'YEC-COM-002',
    categorySlug: 'communication-modules',
    brandSlug: 'sony',
    shortDescription: 'Serial Bluetooth module for wireless control and data exchange.',
    description: 'A serial Bluetooth module often used in robotics, remote switches, device pairing, and training projects.',
    mrp: 289,
    sellingPrice: 245,
    gstPercentage: 18,
    stockQuantity: 37,
    imageCount: 1,
    specifications: [
      { name: 'Bluetooth Version', value: '2.0 + EDR' },
      { name: 'Interface', value: 'UART serial' },
      { name: 'Operating Voltage', value: '3.6V to 6V' },
      { name: 'Mode', value: 'Master/slave configurable' },
    ],
  },
  {
    name: 'SIM800L GSM Module',
    slug: 'sim800l-gsm-module',
    sku: 'YEC-COM-003',
    categorySlug: 'communication-modules',
    brandSlug: 'generic',
    shortDescription: 'Compact GSM module for SMS alerts and remote communication projects.',
    description: 'A small GSM board suited for SMS notifications, remote control units, and telemetry devices requiring cellular access.',
    mrp: 799,
    sellingPrice: 699,
    discountPrice: 649,
    gstPercentage: 18,
    stockQuantity: 11,
    imageCount: 2,
    specifications: [
      { name: 'Network', value: 'Quad-band GSM/GPRS' },
      { name: 'Interface', value: 'UART' },
      { name: 'SIM Support', value: 'Micro SIM' },
      { name: 'Use Case', value: 'SMS, call, and telemetry' },
    ],
  },
  {
    name: 'NEO-6M GPS Module',
    slug: 'neo-6m-gps-module',
    sku: 'YEC-COM-004',
    categorySlug: 'communication-modules',
    brandSlug: 'panasonic',
    shortDescription: 'GPS receiver module for location tracking and timing applications.',
    description: 'A dependable GPS module offering position data for fleet devices, tracking systems, and outdoor electronics projects.',
    mrp: 999,
    sellingPrice: 869,
    gstPercentage: 18,
    stockQuantity: 0,
    imageCount: 2,
    specifications: [
      { name: 'Receiver', value: 'GPS with ceramic antenna' },
      { name: 'Interface', value: 'UART serial' },
      { name: 'Supply Voltage', value: '3V to 5V' },
      { name: 'Use Case', value: 'Tracking and navigation' },
    ],
  },
  {
    name: 'Double Sided Printed Circuit Board Sheet',
    slug: 'double-sided-printed-circuit-board-sheet',
    sku: 'YEC-CPC-001',
    categorySlug: 'computer-and-pcb-components',
    brandSlug: 'yashi',
    shortDescription: 'Copper clad PCB sheet for custom board fabrication and lab work.',
    description: 'A fabrication-ready copper clad sheet intended for custom PCB etching, prototyping, and educational board making.',
    mrp: 199,
    sellingPrice: 169,
    gstPercentage: 18,
    stockQuantity: 63,
    imageCount: 1,
    specifications: [
      { name: 'Board Type', value: 'Double sided copper clad' },
      { name: 'Thickness', value: '1.6mm' },
      { name: 'Sheet Size', value: '10cm x 15cm' },
      { name: 'Material', value: 'FR4' },
    ],
  },
  {
    name: '830 Point Solderless Breadboard',
    slug: '830-point-solderless-breadboard',
    sku: 'YEC-CPC-002',
    categorySlug: 'computer-and-pcb-components',
    brandSlug: 'generic',
    shortDescription: 'Large breadboard for circuit experimentation and rapid prototyping.',
    description: 'A reusable solderless breadboard with ample tie points for microcontroller, sensor, and analog experimentation.',
    mrp: 249,
    sellingPrice: 209,
    discountPrice: 189,
    gstPercentage: 18,
    stockQuantity: 95,
    imageCount: 2,
    specifications: [
      { name: 'Tie Points', value: '830 points' },
      { name: 'Power Rails', value: 'Dual side rails' },
      { name: 'Base', value: 'Self-adhesive backing' },
      { name: 'Use Case', value: 'Prototyping and education' },
    ],
  },
  {
    name: 'Aluminium Heat Sink for TO-220',
    slug: 'aluminium-heat-sink-for-to-220',
    sku: 'YEC-CPC-003',
    categorySlug: 'computer-and-pcb-components',
    brandSlug: 'dell',
    shortDescription: 'Compact heat sink for regulators, transistors, and small power devices.',
    description: 'An aluminium heat sink built to improve thermal performance in regulators, amplifier stages, and compact power electronics.',
    mrp: 49,
    sellingPrice: 39,
    gstPercentage: 18,
    stockQuantity: 140,
    imageCount: 1,
    specifications: [
      { name: 'Compatibility', value: 'TO-220 packages' },
      { name: 'Material', value: 'Anodized aluminium' },
      { name: 'Mounting', value: 'Screw mount' },
      { name: 'Application', value: 'Thermal management' },
    ],
  },
  {
    name: '60mm DC Cooling Fan 12V',
    slug: '60mm-dc-cooling-fan-12v',
    sku: 'YEC-CPC-004',
    categorySlug: 'computer-and-pcb-components',
    brandSlug: 'hp',
    shortDescription: 'Brushless cooling fan for enclosures, SMPS, and compact devices.',
    description: 'A reliable DC cooling fan for electronics cabinets, power supplies, mini PCs, and custom enclosures that need steady airflow.',
    mrp: 199,
    sellingPrice: 169,
    gstPercentage: 18,
    stockQuantity: 6,
    imageCount: 2,
    specifications: [
      { name: 'Fan Size', value: '60mm x 60mm' },
      { name: 'Operating Voltage', value: '12V DC' },
      { name: 'Bearing', value: 'Brushless fan motor' },
      { name: 'Use Case', value: 'Enclosure and SMPS cooling' },
    ],
  },
  {
    name: 'Compact PLC Controller 14 I/O',
    slug: 'compact-plc-controller-14-io',
    sku: 'YEC-IND-001',
    categorySlug: 'industrial-electronics-components',
    brandSlug: 'siemens',
    shortDescription: 'Entry-level PLC for machine control, panels, and process automation.',
    description: 'A compact programmable logic controller designed for machine sequencing, industrial control panels, and automation retrofits.',
    mrp: 14500,
    sellingPrice: 13250,
    discountPrice: 12890,
    gstPercentage: 18,
    stockQuantity: 7,
    isFeatured: true,
    imageCount: 3,
    specifications: [
      { name: 'I/O Count', value: '14 digital I/O' },
      { name: 'Communication', value: 'RS485 / Modbus support' },
      { name: 'Supply Voltage', value: '24V DC' },
      { name: 'Use Case', value: 'Machine and process control' },
    ],
  },
  {
    name: '7 Inch HMI Display Panel',
    slug: '7-inch-hmi-display-panel',
    sku: 'YEC-IND-002',
    categorySlug: 'industrial-electronics-components',
    brandSlug: 'schneider',
    shortDescription: 'Touch HMI panel for operator control and industrial visualization.',
    description: 'A responsive HMI display panel for status monitoring, command entry, and machine-side interface applications.',
    mrp: 18999,
    sellingPrice: 17150,
    gstPercentage: 18,
    stockQuantity: 2,
    imageCount: 3,
    specifications: [
      { name: 'Display Size', value: '7 inches' },
      { name: 'Touch Type', value: 'Resistive touch' },
      { name: 'Ports', value: 'Ethernet and serial' },
      { name: 'Application', value: 'Industrial operator interface' },
    ],
  },
  {
    name: '3 Pole Contactor 32A',
    slug: '3-pole-contactor-32a',
    sku: 'YEC-IND-003',
    categorySlug: 'industrial-electronics-components',
    brandSlug: 'omron',
    shortDescription: 'Industrial contactor for motor control and electrical switching panels.',
    description: 'A robust three-pole contactor used in pump panels, motor starters, control cabinets, and industrial switching systems.',
    mrp: 1499,
    sellingPrice: 1310,
    gstPercentage: 18,
    stockQuantity: 24,
    imageCount: 2,
    specifications: [
      { name: 'Pole Count', value: '3 pole' },
      { name: 'Current Rating', value: '32A' },
      { name: 'Coil Voltage', value: '230V AC' },
      { name: 'Application', value: 'Motor and load switching' },
    ],
  },
  {
    name: 'Miniature Circuit Breaker 16A',
    slug: 'miniature-circuit-breaker-16a',
    sku: 'YEC-IND-004',
    categorySlug: 'industrial-electronics-components',
    brandSlug: 'schneider',
    shortDescription: 'Protection breaker for electrical panels, branch circuits, and equipment.',
    description: 'A dependable breaker for overcurrent protection in control panels, service systems, and machine-side distribution.',
    mrp: 299,
    sellingPrice: 249,
    discountPrice: 229,
    gstPercentage: 18,
    stockQuantity: 78,
    imageCount: 1,
    specifications: [
      { name: 'Current Rating', value: '16A' },
      { name: 'Pole Count', value: 'Single pole' },
      { name: 'Trip Curve', value: 'C curve' },
      { name: 'Application', value: 'Panel and branch circuit protection' },
    ],
  },
]

const seedCatalog = async () => {
  for (const category of categories) {
    await prisma.category.upsert({
      where: { slug: category.slug },
      update: {
        name: category.name,
        description: category.description,
        isActive: true,
      },
      create: {
        name: category.name,
        slug: category.slug,
        description: category.description,
        isActive: true,
      },
    })
  }

  for (const brand of brands) {
    await prisma.brand.upsert({
      where: { slug: brand.slug },
      update: {
        name: brand.name,
        description: brand.description,
        isActive: true,
      },
      create: {
        name: brand.name,
        slug: brand.slug,
        description: brand.description,
        isActive: true,
      },
    })
  }

  for (const product of products) {
    const images = Array.from({ length: product.imageCount }, (_, index) => ({
      imageUrl: placeholderImageUrl(product.name, index + 1),
      altText: `${product.name} image ${index + 1}`,
      sortOrder: index,
    }))

    await prisma.product.upsert({
      where: { slug: product.slug },
      update: {
        category: {
          connect: { slug: product.categorySlug },
        },
        brand: product.brandSlug
          ? {
              connect: { slug: product.brandSlug },
            }
          : {
              disconnect: true,
            },
        name: product.name,
        sku: product.sku,
        shortDescription: product.shortDescription,
        description: product.description,
        mrp: product.mrp,
        sellingPrice: product.sellingPrice,
        discountPrice: product.discountPrice,
        gstPercentage: product.gstPercentage,
        stockQuantity: product.stockQuantity,
        isActive: true,
        isFeatured: product.isFeatured ?? false,
        images: {
          deleteMany: {},
          create: images,
        },
        specifications: {
          deleteMany: {},
          create: product.specifications,
        },
      },
      create: {
        category: {
          connect: { slug: product.categorySlug },
        },
        brand: product.brandSlug
          ? {
              connect: { slug: product.brandSlug },
            }
          : undefined,
        name: product.name,
        slug: product.slug,
        sku: product.sku,
        shortDescription: product.shortDescription,
        description: product.description,
        mrp: product.mrp,
        sellingPrice: product.sellingPrice,
        discountPrice: product.discountPrice,
        gstPercentage: product.gstPercentage,
        stockQuantity: product.stockQuantity,
        isActive: true,
        isFeatured: product.isFeatured ?? false,
        images: {
          create: images,
        },
        specifications: {
          create: product.specifications,
        },
      },
    })
  }
}

const run = async () => {
  await seedCatalog()
  process.stdout.write(`Seeded ${categories.length} categories, ${brands.length} brands, and ${products.length} products.\n`)
}

run()
  .catch((error) => {
    process.stderr.write(`Seeding failed: ${error instanceof Error ? error.message : String(error)}\n`)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
